# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from uis.resources.stylesheets import *

class Ui_MainWindow(object):
    def __init__(self, parent=None):
        self.parent = parent


    def setupUi(self, MainWindow):
        self.window = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_gosia = QtWidgets.QLabel(self.centralwidget)
        self.label_gosia.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gosia.setObjectName("label_gosia")
        self.gridLayout_3.addWidget(self.label_gosia, 0, 1, 1, 1)
        self.label_gosia_img = QtWidgets.QLabel(self.centralwidget)
        self.label_gosia_img.setObjectName("label_gosia_img")
        self.gridLayout_3.addWidget(self.label_gosia_img, 1, 1, 1, 1)
        self.label_gosia_desc = QtWidgets.QLabel(self.centralwidget)
        self.label_gosia_desc.setObjectName("label_gosia_desc")
        self.gridLayout_3.addWidget(self.label_gosia_desc, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 10)
        self.gridLayout_3.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_ewa_desc = QtWidgets.QLabel(self.centralwidget)
        self.label_ewa_desc.setObjectName("label_ewa_desc")
        self.gridLayout_4.addWidget(self.label_ewa_desc, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.label_ewa_img = QtWidgets.QLabel(self.centralwidget)
        self.label_ewa_img.setObjectName("label_ewa_img")
        self.gridLayout_4.addWidget(self.label_ewa_img, 1, 1, 1, 1)
        self.label_ewa = QtWidgets.QLabel(self.centralwidget)
        self.label_ewa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ewa.setObjectName("label_ewa")
        self.gridLayout_4.addWidget(self.label_ewa, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 10)
        self.gridLayout_4.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_ula = QtWidgets.QLabel(self.centralwidget)
        self.label_ula.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ula.setObjectName("label_ula")
        self.gridLayout_5.addWidget(self.label_ula, 0, 1, 1, 1)
        self.label_ula_img = QtWidgets.QLabel(self.centralwidget)
        self.label_ula_img.setObjectName("label_ula_img")
        self.gridLayout_5.addWidget(self.label_ula_img, 1, 1, 1, 1)
        self.label_ula_desc = QtWidgets.QLabel(self.centralwidget)
        self.label_ula_desc.setObjectName("label_ula_desc")
        self.gridLayout_5.addWidget(self.label_ula_desc, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout_5.setRowStretch(0, 1)
        self.gridLayout_5.setRowStretch(1, 10)
        self.gridLayout_5.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_maciek_s_img = QtWidgets.QLabel(self.centralwidget)
        self.label_maciek_s_img.setObjectName("label_maciek_s_img")
        self.gridLayout_7.addWidget(self.label_maciek_s_img, 1, 1, 1, 1)
        self.label_maciek_s = QtWidgets.QLabel(self.centralwidget)
        self.label_maciek_s.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maciek_s.setObjectName("label_maciek_s")
        self.gridLayout_7.addWidget(self.label_maciek_s, 0, 1, 1, 1)
        self.label_maciek_s_desc = QtWidgets.QLabel(self.centralwidget)
        self.label_maciek_s_desc.setObjectName("label_maciek_s_desc")
        self.gridLayout_7.addWidget(self.label_maciek_s_desc, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridLayout_7.setRowStretch(0, 1)
        self.gridLayout_7.setRowStretch(1, 10)
        self.gridLayout_7.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 2, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 2, 1, 1)
        self.label_maciek_w = QtWidgets.QLabel(self.centralwidget)
        self.label_maciek_w.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maciek_w.setObjectName("label_maciek_w")
        self.gridLayout.addWidget(self.label_maciek_w, 0, 1, 1, 1)
        self.label_maciek_w_desc = QtWidgets.QLabel(self.centralwidget)
        self.label_maciek_w_desc.setObjectName("label_maciek_w_desc")
        self.gridLayout.addWidget(self.label_maciek_w_desc, 2, 1, 1, 1)
        self.label_maciek_w_img = QtWidgets.QLabel(self.centralwidget)
        self.label_maciek_w_img.setObjectName("label_maciek_w_img")
        self.gridLayout.addWidget(self.label_maciek_w_img, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 10)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_kuba = QtWidgets.QLabel(self.centralwidget)
        self.label_kuba.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kuba.setObjectName("label_kuba")
        self.gridLayout_6.addWidget(self.label_kuba, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 1, 0, 1, 1)
        self.label_kuba_desc = QtWidgets.QLabel(self.centralwidget)
        self.label_kuba_desc.setObjectName("label_kuba_desc")
        self.gridLayout_6.addWidget(self.label_kuba_desc, 2, 1, 1, 1)
        self.label_kuba_img = QtWidgets.QLabel(self.centralwidget)
        self.label_kuba_img.setObjectName("label_kuba_img")
        self.gridLayout_6.addWidget(self.label_kuba_img, 1, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 1, 2, 1, 1)
        self.gridLayout_6.setRowStretch(0, 1)
        self.gridLayout_6.setRowStretch(1, 10)
        self.gridLayout_6.setRowStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.button_return = QtWidgets.QPushButton(self.centralwidget)
        self.button_return.setObjectName("button_return")
        self.horizontalLayout.addWidget(self.button_return)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setStyleSheet(gradient_style_sheet)
        self.centralwidget.setStyleSheet(button_with_image_style_sheet_colored_font)
        self.label.setStyleSheet(pretty_big_label_style_sheet)

        self.label_ula_img.setMaximumSize(QtCore.QSize(200, 200))
        self.label_ula_img.setText("")
        self.label_ula_img.setPixmap(QtGui.QPixmap("resources/people/ula.jpg"))
        self.label_ula_img.setScaledContents(True)
        self.label_ula_img.setAlignment(QtCore.Qt.AlignCenter)

        self.label_kuba_img.setMaximumSize(QtCore.QSize(200, 200))
        self.label_kuba_img.setText("")
        self.label_kuba_img.setPixmap(QtGui.QPixmap("resources/people/kuba.jpg"))
        self.label_kuba_img.setScaledContents(True)
        self.label_kuba_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kuba_img.setStyleSheet("border-radius: 25%;")

        self.label_maciek_s_img.setMaximumSize(QtCore.QSize(200, 200))
        self.label_maciek_s_img.setText("")
        self.label_maciek_s_img.setPixmap(QtGui.QPixmap("resources/groups/g4.png"))
        self.label_maciek_s_img.setScaledContents(True)
        self.label_maciek_s_img.setAlignment(QtCore.Qt.AlignCenter)

        self.label_maciek_w_img.setMaximumSize(QtCore.QSize(200, 200))
        self.label_maciek_w_img.setText("")
        self.label_maciek_w_img.setPixmap(QtGui.QPixmap("resources/people/maciek_w.jpg"))
        self.label_maciek_w_img.setScaledContents(True)
        self.label_maciek_w_img.setAlignment(QtCore.Qt.AlignCenter)

        self.label_ewa_img.setMaximumSize(QtCore.QSize(200, 200))
        self.label_ewa_img.setText("")
        self.label_ewa_img.setPixmap(QtGui.QPixmap("resources/people/ewa.jpg"))
        self.label_ewa_img.setScaledContents(True)
        self.label_ewa_img.setAlignment(QtCore.Qt.AlignCenter)

        self.label_gosia_img.setMaximumSize(QtCore.QSize(200, 200))
        self.label_gosia_img.setText("")
        self.label_gosia_img.setPixmap(QtGui.QPixmap("resources/people/gosia.jpg"))
        self.label_gosia_img.setScaledContents(True)
        self.label_gosia_img.setAlignment(QtCore.Qt.AlignCenter)

        self.return_pixmap = QtGui.QPixmap("resources/return.png")
        self.return_pixmap = self.return_pixmap.scaled(QtCore.QSize(32,32))
        self.icon = QtGui.QIcon(self.return_pixmap)
        self.button_return.setIcon(self.icon)
        self.button_return.setIconSize(QtCore.QSize(32, 32))

        self.button_return.clicked.connect(self.clicked_return)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Our team:"))
        self.label_gosia.setText(_translate("MainWindow", "Gosia Barnach:"))
        self.label_gosia_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_gosia_desc.setText(_translate("MainWindow", "Front-end developer"))
        self.label_ewa.setText(_translate("MainWindow", "Ewa Tabor:"))
        self.label_ewa_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_ewa_desc.setText(_translate("MainWindow", "Front-end developer"))
        self.label_ula.setText(_translate("MainWindow", "Ula Krywalska:"))
        self.label_ula_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_ula_desc.setText(_translate("MainWindow", "Product owner"))
        self.label_maciek_s.setText(_translate("MainWindow", "Maciek Syska:"))
        self.label_maciek_s_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_maciek_s_desc.setText(_translate("MainWindow", "Back-end developer"))
        self.label_maciek_w.setText(_translate("MainWindow", "Maciek Wilk:"))
        self.label_maciek_w_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_maciek_w_desc.setText(_translate("MainWindow", "Front-end developer"))
        self.label_kuba.setText(_translate("MainWindow", "Kuba Komnata:"))
        self.label_kuba_img.setText(_translate("MainWindow", "TextLabel"))
        self.label_kuba_desc.setText(_translate("MainWindow", "Back-end developer"))

    def clicked_return(self):
        self.parent.window.show()
        self.window.hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginpageWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(LoginpageWindow)
    LoginpageWindow.show()
    sys.exit(app.exec_())